[package]
authors = ["Ballerina"]
distribution = "2201.12.3"
export = ["health.hl7v2.utils.v2tofhirr4"]
keywords = ["Healthcare", "HL7", "FHIR"]
name = "health.hl7v2.utils.v2tofhirr4"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"
version = "4.0.0"

[build-options]
optimizeDependencyCompilation = true
