[package]
org = "ballerinax"
name = "health.hl7v231"
version = "1.0.0"
authors=["Ballerina"]
keywords=["Healthcare", "HL7", "HL7v2.3.1"]
distribution = "2201.4.1"
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "1.0.3"
