[package]
org = "ballerinax"
name = "health.hl7v25"
version = "1.0.0"
authors=["Ballerina"]
keywords=["Healthcare", "HL7", "HL7v2.5"]
distribution = "2201.4.1"
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "1.0.2"
