[package]
org = "ballerinax"
name = "health.hl7v23.utils.v2tofhirr4"
version = "1.0.0"
distribution = "2201.12.10"
authors = ["Ballerina"]
keywords = ["Healthcare", "HL7", "FHIR"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

[build-options]
optimizeDependencyCompilation = true
