[package]
org = "ballerinax"
name = "health.hl7v23"
version = "4.0.3"
authors=["Ballerina"]
keywords=["Healthcare", "HL7", "HL7v2.3"]
distribution = "2201.12.3"
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"
