[package]
org = "ballerinax"
name = "health.hl7v23"
version = "2.0.1"
authors=["Ballerina"]
keywords=["Healthcare", "HL7", "HL7v2.3"]
distribution = "2201.6.0"
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "2.0.0"
