[package]
org = "ballerinax"
name = "health.hl7v23"
version = "1.0.7-snapshot"
authors=["Ballerina"]
keywords=["Healthcare", "HL7", "HL7v2.3"]
distribution = "2201.5.0"
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "1.0.5"
