[package]
org = "ballerinax"
name = "health.hl7v2"
version = "3.0.8"
authors=["Ballerina"]
keywords=["Healthcare", "HL7"]
distribution = "2201.12.3"
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

