[package]
org = "ballerinax"
name = "health.hl7v2"
version = "2.1.1"
authors=["Ballerina"]
keywords=["Healthcare", "HL7"]
distribution = "2201.8.1"
export=["health.hl7v2"]
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"
