[package]
org = "ballerinax"
name = "health.hl7v27"
version = "1.0.3-snapshot"
authors=["WSO2 Healthcare"]
keywords=["Healthcare", "HL7", "HL7v2.7"]
distribution = "2201.5.0"
repository="https://github.com/ballerina-platform/module-ballerinax-health.hl7v2"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "1.0.5"
